slang: new package at 2.3.2
kiss-community/community pull request #432
Opened 2021-05-29 02:34 UTC by AndreiSva

Please fill out the template.

Read: https://k1sslinux.org/wiki/kiss/style-guide

Please include the manifest for version bumps and new packages.

---

## Description of package
The S-lang scripting language is used for a few popular programs mainly the Most pager.

## Installed manifest of package

(`kiss manifest <pkg>`)

```
/var/db/kiss/installed/slang/version
/var/db/kiss/installed/slang/sources
/var/db/kiss/installed/slang/manifest
/var/db/kiss/installed/slang/depends
/var/db/kiss/installed/slang/checksums
/var/db/kiss/installed/slang/build
/var/db/kiss/installed/slang/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/local/share/slsh/zlib.sl
/usr/local/share/slsh/varray.sl
/usr/local/share/slsh/termios.sl
/usr/local/share/slsh/sysconf.sl
/usr/local/share/slsh/structfuns.sl
/usr/local/share/slsh/stkcheck.sl
/usr/local/share/slsh/statslib/kuiper.sl
/usr/local/share/slsh/statslib/ks_test.sl
/usr/local/share/slsh/statslib/ad_test.sl
/usr/local/share/slsh/statslib/
/usr/local/share/slsh/stats.sl
/usr/local/share/slsh/socket.sl
/usr/local/share/slsh/slsmg.sl
/usr/local/share/slsh/slshrl.sl
/usr/local/share/slsh/slshhelp.sl
/usr/local/share/slsh/sldbsock.sl
/usr/local/share/slsh/sldbcore.sl
/usr/local/share/slsh/sldb.sl
/usr/local/share/slsh/setfuns.sl
/usr/local/share/slsh/select.sl
/usr/local/share/slsh/scripts/svnsh
/usr/local/share/slsh/scripts/slstkchk
/usr/local/share/slsh/scripts/slprof
/usr/local/share/slsh/scripts/sldb
/usr/local/share/slsh/scripts/lsrpm
/usr/local/share/slsh/scripts/jpegsize
/usr/local/share/slsh/scripts/
/usr/local/share/slsh/rline/vikeys.sl
/usr/local/share/slsh/rline/slrline.rc
/usr/local/share/slsh/rline/histsrch.sl
/usr/local/share/slsh/rline/history.sl
/usr/local/share/slsh/rline/emacskeys.sl
/usr/local/share/slsh/rline/editor.sl
/usr/local/share/slsh/rline/editfuns.sl
/usr/local/share/slsh/rline/complete.sl
/usr/local/share/slsh/rline/
/usr/local/share/slsh/require.sl
/usr/local/share/slsh/readascii.sl
/usr/local/share/slsh/rand.sl
/usr/local/share/slsh/profile.sl
/usr/local/share/slsh/process.sl
/usr/local/share/slsh/print.sl
/usr/local/share/slsh/png.sl
/usr/local/share/slsh/pcre.sl
/usr/local/share/slsh/onig.sl
/usr/local/share/slsh/local-packages/
/usr/local/share/slsh/listfuns.sl
/usr/local/share/slsh/json.sl
/usr/local/share/slsh/iconv.sl
/usr/local/share/slsh/histogram.sl
/usr/local/share/slsh/help/structfuns.hlp
/usr/local/share/slsh/help/statsfuns.hlp
/usr/local/share/slsh/help/sockfuns.hlp
/usr/local/share/slsh/help/slsmg.hlp
/usr/local/share/slsh/help/setfuns.hlp
/usr/local/share/slsh/help/require.hlp
/usr/local/share/slsh/help/readascii.hlp
/usr/local/share/slsh/help/randfuns.hlp
/usr/local/share/slsh/help/profile.hlp
/usr/local/share/slsh/help/process.hlp
/usr/local/share/slsh/help/print.hlp
/usr/local/share/slsh/help/pngfuns.hlp
/usr/local/share/slsh/help/pcrefuns.hlp
/usr/local/share/slsh/help/onigfuns.hlp
/usr/local/share/slsh/help/listfuns.hlp
/usr/local/share/slsh/help/jsonfuns.hlp
/usr/local/share/slsh/help/histfuns.hlp
/usr/local/share/slsh/help/glob.hlp
/usr/local/share/slsh/help/fswalk.hlp
/usr/local/share/slsh/help/forkfuns.hlp
/usr/local/share/slsh/help/csvfuns.hlp
/usr/local/share/slsh/help/cmdopt.hlp
/usr/local/share/slsh/help/chksumfuns.hlp
/usr/local/share/slsh/help/base64funs.hlp
/usr/local/share/slsh/help/arrayfuns.hlp
/usr/local/share/slsh/help/
/usr/local/share/slsh/glob.sl
/usr/local/share/slsh/fswalk.sl
/usr/local/share/slsh/fork.sl
/usr/local/share/slsh/fcntl.sl
/usr/local/share/slsh/csv.sl
/usr/local/share/slsh/cmdopt.sl
/usr/local/share/slsh/cmaps/wysiwyg.map
/usr/local/share/slsh/cmaps/topo.map
/usr/local/share/slsh/cmaps/split.map
/usr/local/share/slsh/cmaps/seis.map
/usr/local/share/slsh/cmaps/sealand.map
/usr/local/share/slsh/cmaps/relief.map
/usr/local/share/slsh/cmaps/red2green.map
/usr/local/share/slsh/cmaps/rainbow.map
/usr/local/share/slsh/cmaps/polar.map
/usr/local/share/slsh/cmaps/ocean.map
/usr/local/share/slsh/cmaps/no_green.map
/usr/local/share/slsh/cmaps/jet.map
/usr/local/share/slsh/cmaps/hot.map
/usr/local/share/slsh/cmaps/haxby.map
/usr/local/share/slsh/cmaps/gray.map
/usr/local/share/slsh/cmaps/globe.map
/usr/local/share/slsh/cmaps/gebco.map
/usr/local/share/slsh/cmaps/edge.map
/usr/local/share/slsh/cmaps/ds9sls.map
/usr/local/share/slsh/cmaps/ds9b.map
/usr/local/share/slsh/cmaps/drywet.map
/usr/local/share/slsh/cmaps/cubicyf.map
/usr/local/share/slsh/cmaps/cubicl.map
/usr/local/share/slsh/cmaps/copper.map
/usr/local/share/slsh/cmaps/coolwarm.map
/usr/local/share/slsh/cmaps/cool.map
/usr/local/share/slsh/cmaps/
/usr/local/share/slsh/chksum.sl
/usr/local/share/slsh/base64.sl
/usr/local/share/slsh/autoload.sl
/usr/local/share/slsh/arrayfuns.sl
/usr/local/share/slsh/
/usr/local/share/man/man1/slsh.1
/usr/local/share/man/man1/
/usr/local/share/man/
/usr/local/share/doc/slsh/html/slshfun.html
/usr/local/share/doc/slsh/html/slshfun-9.html
/usr/local/share/doc/slsh/html/slshfun-8.html
/usr/local/share/doc/slsh/html/slshfun-7.html
/usr/local/share/doc/slsh/html/slshfun-6.html
/usr/local/share/doc/slsh/html/slshfun-5.html
/usr/local/share/doc/slsh/html/slshfun-4.html
/usr/local/share/doc/slsh/html/slshfun-3.html
/usr/local/share/doc/slsh/html/slshfun-2.html
/usr/local/share/doc/slsh/html/slshfun-13.html
/usr/local/share/doc/slsh/html/slshfun-12.html
/usr/local/share/doc/slsh/html/slshfun-11.html
/usr/local/share/doc/slsh/html/slshfun-10.html
/usr/local/share/doc/slsh/html/slshfun-1.html
/usr/local/share/doc/slsh/html/
/usr/local/share/doc/slsh/
/usr/local/share/doc/slang/v2/slangfun.txt
/usr/local/share/doc/slang/v2/slangdoc.html
/usr/local/share/doc/slang/v2/slang.txt
/usr/local/share/doc/slang/v2/cslang.txt
/usr/local/share/doc/slang/v2/cref.txt
/usr/local/share/doc/slang/v2/changes.txt
/usr/local/share/doc/slang/v2/COPYING
/usr/local/share/doc/slang/v2/
/usr/local/share/doc/slang/
/usr/local/share/doc/
/usr/local/share/
/usr/local/lib/slang/v2/modules/zlib-module.so
/usr/local/lib/slang/v2/modules/varray-module.so
/usr/local/lib/slang/v2/modules/termios-module.so
/usr/local/lib/slang/v2/modules/sysconf-module.so
/usr/local/lib/slang/v2/modules/stats-module.so
/usr/local/lib/slang/v2/modules/socket-module.so
/usr/local/lib/slang/v2/modules/slsmg-module.so
/usr/local/lib/slang/v2/modules/select-module.so
/usr/local/lib/slang/v2/modules/rand-module.so
/usr/local/lib/slang/v2/modules/json-module.so
/usr/local/lib/slang/v2/modules/iconv-module.so
/usr/local/lib/slang/v2/modules/histogram-module.so
/usr/local/lib/slang/v2/modules/fork-module.so
/usr/local/lib/slang/v2/modules/fcntl-module.so
/usr/local/lib/slang/v2/modules/csv-module.so
/usr/local/lib/slang/v2/modules/chksum-module.so
/usr/local/lib/slang/v2/modules/base64-module.so
/usr/local/lib/slang/v2/modules/
/usr/local/lib/slang/v2/
/usr/local/lib/slang/
/usr/local/lib/pkgconfig/slang.pc
/usr/local/lib/pkgconfig/
/usr/local/lib/libslang.so.2.3.2
/usr/local/lib/libslang.so.2
/usr/local/lib/libslang.so
/usr/local/lib/
/usr/local/include/slcurses.h
/usr/local/include/slang.h
/usr/local/include/
/usr/local/etc/slsh.rc
/usr/local/etc/
/usr/local/bin/slsh
/usr/local/bin/
/usr/local/
/usr/
```

## New package

- [X] Latest upstream version.
- [ ] I agree to maintain this package.
- [ ] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

2021-06-02 18:21 UTC, dilyn-corner requested changes
This PR is two commits adding two packages; they should be separated out.

2021-06-02 18:21 UTC, dilyn-corner commented on community/slang/build
> +./configure
Should be: 
```
./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make...
```

2021-06-02 18:21 UTC, dilyn-corner commented on community/slang/build
> +make DESTDIR="$1" install
Looks like you'll have to specify `make -j1; make -j1 DESTDIR="$1" install` otherwise the build eats itself because it doesn't like parallel jobs...

2021-06-03 15:26 UTC, dilyn-corner requested changes

2021-06-03 15:26 UTC, dilyn-corner commented on community/slang/build
> +make -j1
Just add a linebreak here and lgtm

2021-06-03 19:23 UTC, AndreiSva commented on community/slang/build
> +make -j1
done!

2021-06-03 21:48 UTC, merged

2021-06-04 03:07 UTC, AndreiSva commented
@dilyn-corner I just realized I submitted the pull request with an inconsistent commit message :(.

2021-06-04 06:05 UTC, AndreiSva commented
#444